version: '3.8'

services:
  backend:
    build: ./backend
    env_file:             
      - ./backend/.env 
    ports:
      - '3001:3001'
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/prisma:/app/prisma

  frontend:
    build: ./frontend
    ports:
      - '8080:80'
